package com.ghiles.quizubuntu;
import org.junit.Test;
import static org.junit.Assert.*;
public class S03CommandsTest {
    private String ok(VirtualMachine v,String command){VirtualMachine.Result r=v.execute(command);assertEquals(command+" -> "+r.text,0,r.exitCode);return r.text;}
    private void denied(VirtualMachine v,String command){assertNotEquals(command,0,v.execute(command).exitCode);}
    @Test public void usersGroupsAndContextFollowFirstPdfChallenge(){
        VirtualMachine v=new VirtualMachine();denied(v,"useradd -m intrus");ok(v,"sudo -i");
        for(int i=1;i<=3;i++)ok(v,"useradd -m -s /bin/bash wilder"+i);
        ok(v,"groupadd groupetest");ok(v,"addgroup groupeadmin");
        ok(v,"usermod -a -G groupetest wilder1");ok(v,"usermod -aG groupetest,groupeadmin wilder2");ok(v,"usermod -G groupeadmin wilder3");
        assertTrue(ok(v,"id wilder2").contains("groupetest"));assertTrue(ok(v,"id wilder2").contains("groupeadmin"));assertFalse(ok(v,"id wilder3").contains("groupetest"));
        assertTrue(ok(v,"cat /etc/passwd | grep wilder1").contains("/home/wilder1:/bin/bash"));assertTrue(ok(v,"cat /etc/group | grep groupetest").contains("wilder1,wilder2"));
        ok(v,"passwd wilder1");ok(v,"su - wilder1");assertEquals("wilder1\n",ok(v,"whoami"));ok(v,"touch fichier.txt");assertTrue(ok(v,"ls -l | cat").contains("wilder1 wilder1"));
        denied(v,"cat /etc/shadow");denied(v,"sudo cat /etc/shadow");ok(v,"exit");assertEquals("root\n",ok(v,"whoami"));ok(v,"cat /etc/shadow | head -1");ok(v,"exit");assertEquals("ubuntu\n",ok(v,"whoami"));assertEquals("/home/ubuntu",ok(v,"pwd"));
    }
    @Test public void usermodWithoutAppendReplacesOnlySupplementaryGroups(){VirtualMachine v=new VirtualMachine();ok(v,"sudo useradd -m wilder");ok(v,"sudo groupadd a");ok(v,"sudo groupadd b");ok(v,"sudo usermod -aG a,b wilder");ok(v,"sudo usermod -G b wilder");assertEquals("wilder b\n",ok(v,"groups wilder"));denied(v,"sudo usermod -aG absent wilder");assertEquals("wilder b\n",ok(v,"groups wilder"));}
    @Test public void permissionNotationAndDirectoryTraversal(){VirtualMachine v=new VirtualMachine();v.prepareScenario("s03-permissions");ok(v,"touch test.txt");ok(v,"chmod u=rwx,g=rx,o=r test.txt");assertTrue(ok(v,"ls -l | cat").contains("-rwxr-xr--"));ok(v,"chmod 740 test.txt");assertTrue(ok(v,"stat test.txt").contains("0740"));
        ok(v,"mkdir testdir");ok(v,"touch testdir/fichier.txt");ok(v,"chmod u-x testdir");denied(v,"cd testdir");denied(v,"cat testdir/fichier.txt");ok(v,"chmod u+x testdir");ok(v,"cd testdir");ok(v,"cd ..");
        ok(v,"sudo chown -R root:groupetest testdir");assertTrue(ok(v,"ls -l testdir | cat").contains("root groupetest"));denied(v,"chmod 777 testdir/fichier.txt");denied(v,"sudo chown inconnu test.txt");}
    @Test public void umaskIsBitwiseAndNotRetroactive(){VirtualMachine v=new VirtualMachine();ok(v,"touch before");ok(v,"umask 077");ok(v,"touch secret");ok(v,"mkdir prive");assertTrue(ok(v,"stat secret").contains("0600"));assertTrue(ok(v,"stat prive").contains("0700"));assertTrue(ok(v,"stat before").contains("0644"));ok(v,"umask 033");ok(v,"echo note > bits");assertTrue(ok(v,"stat bits").contains("0644"));}
    @Test public void sgidStickyAndNamedAclHaveObservableEffects(){VirtualMachine v=new VirtualMachine();ok(v,"sudo useradd -m alice");ok(v,"sudo useradd -m bob");ok(v,"sudo useradd -m invite");ok(v,"sudo groupadd equipe");ok(v,"sudo usermod -aG equipe alice");ok(v,"sudo usermod -aG equipe bob");ok(v,"sudo mkdir /tmp/partage");ok(v,"sudo chown root:equipe /tmp/partage");ok(v,"sudo chmod 3770 /tmp/partage");ok(v,"su alice");ok(v,"touch /tmp/partage/alice.txt");ok(v,"mkdir /tmp/partage/sous");assertTrue(ok(v,"stat /tmp/partage/alice.txt").contains("Groupe : equipe"));assertTrue(ok(v,"stat /tmp/partage/sous").contains("02755"));ok(v,"exit");ok(v,"su bob");denied(v,"rm /tmp/partage/alice.txt");ok(v,"touch /tmp/partage/bob.txt");ok(v,"rm /tmp/partage/bob.txt");ok(v,"exit");ok(v,"su invite");denied(v,"ls /tmp/partage");ok(v,"exit");ok(v,"sudo setfacl -m u:invite:rx /tmp/partage");assertTrue(ok(v,"getfacl /tmp/partage").contains("user:invite:r-x"));ok(v,"su invite");ok(v,"cd /tmp/partage");assertTrue(ok(v,"ls | cat").contains("alice.txt"));denied(v,"touch interdit.txt");}
    @Test public void aclGrantRevokeAndMaskLimitReadAccess(){VirtualMachine v=new VirtualMachine();ok(v,"sudo useradd -m wilder");ok(v,"echo contenu > /tmp/secret");ok(v,"sudo chown root /tmp/secret");ok(v,"sudo chmod 600 /tmp/secret");ok(v,"su wilder");denied(v,"cat /tmp/secret");ok(v,"exit");ok(v,"sudo setfacl -m u:wilder:r /tmp/secret");ok(v,"su wilder");assertEquals("contenu\n",ok(v,"cat /tmp/secret"));denied(v,"echo ecraser > /tmp/secret");ok(v,"exit");ok(v,"sudo chmod 600 /tmp/secret");ok(v,"su wilder");denied(v,"cat /tmp/secret");ok(v,"exit");ok(v,"sudo setfacl -x u:wilder /tmp/secret");assertFalse(ok(v,"getfacl /tmp/secret").contains("user:wilder:"));}
    @Test public void suidWhoamiAndFindSpecialBits(){VirtualMachine v=new VirtualMachine();ok(v,"cp /usr/bin/whoami ~/mon-whoami");assertEquals("ubuntu\n",ok(v,"./mon-whoami"));ok(v,"sudo chown root mon-whoami");ok(v,"sudo chmod u+s mon-whoami");assertEquals("root\n",ok(v,"./mon-whoami"));assertTrue(ok(v,"ls -l mon-whoami | cat").contains("-rwsr-xr-x"));assertTrue(ok(v,"find / -perm -4000 2>/dev/null").contains("mon-whoami"));ok(v,"sudo chmod u-s mon-whoami");assertEquals("ubuntu\n",ok(v,"./mon-whoami"));assertTrue(ok(v,"find / -perm -1000 2>/dev/null").contains("/tmp"));}
    @Test public void virtualBoxFullPdfCreationAndStateTransitions(){VirtualMachine v=new VirtualMachine();v.prepareScenario("s03-vbox");ok(v,"vboxmanage createvm --name Ubuntu10 --ostype Ubuntu_64 --register");ok(v,"VBoxManage modifyvm Ubuntu10 --memory 2048 --graphicscontroller VMSVGA --vram 16");ok(v,"VBoxManage storagectl Ubuntu10 --name 'SATA Controller' --add sata --controller IntelAhci");ok(v,"VBoxManage createmedium disk --filename '~/VirtualBox VMs/Ubuntu10/Ubuntu10.vmdk' --size 30000 --format VMDK");ok(v,"VBoxManage storageattach Ubuntu10 --storagectl 'SATA Controller' --port 0 --device 0 --type hdd --medium '~/VirtualBox VMs/Ubuntu10/Ubuntu10.vmdk'");ok(v,"VBoxManage storagectl Ubuntu10 --name 'IDE Controller' --add ide");ok(v,"VBoxManage storageattach Ubuntu10 --storagectl 'IDE Controller' --port 1 --device 0 --type dvddrive --medium ~/Documents/ubuntu.iso");ok(v,"VBoxManage modifyvm Ubuntu10 --nic1 nat");assertTrue(ok(v,"VBoxManage showvminfo Ubuntu10").contains("memory: 2048"));ok(v,"VBoxManage snapshot Ubuntu10 take initial");ok(v,"VBoxManage modifyvm Ubuntu10 --memory 4096");ok(v,"VBoxManage snapshot Ubuntu10 restore initial");assertTrue(ok(v,"VBoxManage showvminfo Ubuntu10").contains("memory: 2048"));ok(v,"VBoxManage startvm Ubuntu10 --type gui");assertTrue(ok(v,"VBoxManage list runningvms").contains("Ubuntu10"));denied(v,"VBoxManage modifyvm Ubuntu10 --memory 512");ok(v,"VBoxManage controlvm Ubuntu10 pause");ok(v,"VBoxManage controlvm Ubuntu10 resume");ok(v,"VBoxManage controlvm Ubuntu10 acpipowerbutton");assertFalse(ok(v,"VBoxManage list runningvms").contains("Ubuntu10"));ok(v,"VBoxManage clonemedium disk '~/VirtualBox VMs/Template/template.vmdk' '~/VirtualBox VMs/Copie/copie.vmdk' --format VMDK");denied(v,"VBoxManage startvm absente");denied(v,"VBoxManage modifyvm Ubuntu10 --unknown yes");}
    @Test public void windowsPathsRemainDistinctAndCaseInsensitive(){VirtualMachine v=new VirtualMachine();ok(v,"cmd");ok(v,"cd C:\\Users\\ubuntu");ok(v,"mkdir Secured");ok(v,"cd secured");ok(v,"echo Bonjour > note.txt");assertTrue(ok(v,"dir").contains("note.txt"));assertEquals("Bonjour\n",ok(v,"type NOTE.TXT"));ok(v,"cd ..");assertTrue(ok(v,"dir").contains("Secured"));ok(v,"exit");assertEquals("/home/ubuntu",ok(v,"pwd"));denied(v,"cat Secured/note.txt");assertTrue(ok(v,"cmd /c dir C:\\Users\\ubuntu\\Secured").contains("note.txt"));assertEquals("ubuntu\n",ok(v,"whoami"));}
}
