package com.ghiles.quizubuntu;
import java.util.ArrayList;
import java.util.List;
/** Additional practice derives only from the five attached course PDFs. */
final class PdfPracticeBank {
    private static MainActivity.Question typed(int level,String category,String format,String question,String explanation,String example,String... accepted) {
        return new MainActivity.Question(level,category,question,0,explanation,example,accepted[0]).written(format,accepted);
    }
    static List<MainActivity.Question> questions() {
        List<MainActivity.Question> q=new ArrayList<>();
        q.add(typed(1,"Bash","Commande à écrire","Affiche le chemin du dossier courant. Tape une commande.","Fiche Bash S01 — pwd affiche un chemin ; ls liste des entrées, cd change de dossier.","$ pwd\n/home/ubuntu/projet","pwd"));
        q.add(typed(1,"Bash","Corriger une commande","On veut remonter d’un dossier. Corrige : cd .","Fiche Bash S01 — . désigne le dossier courant ; .. désigne son parent.","/home/ubuntu/projet $ cd ..\n/home/ubuntu $","cd .."));
        q.add(typed(1,"Bash","Commande à écrire","Liste les fichiers cachés avec les détails. Tape une seule commande ls.","Fiche Bash S01 et Guide Git débutant Ubuntu — -a inclut les noms commençant par un point ; -l donne les détails. .git est un dossier caché.","git init\nls -la\n# .git apparaît","ls -la","ls -al","ls -l -a","ls -a -l"));
        q.add(typed(1,"Bash","Prédire le résultat","Le fichier notes.txt contient bonjour. Après echo suite >> notes.txt, quel mot figure sur la dernière ligne ?","Fiche Bash S01 — >> ajoute à la fin ; > remplace le contenu.","bonjour\nsuite","suite"));
        q.add(new MainActivity.Question(1,"Bash","Piège annoncé : laquelle affiche le dossier courant ? Tu peux choisir « Aucune ».",4,"Fiche Bash S01 — la réponse est pwd. cd déplace, ls liste, mkdir crée, clear efface l’affichage. Aucun de ces quatre choix n’affiche le chemin courant.","$ pwd\n/home/ubuntu","cd ..","ls","mkdir dossier","clear","Aucune de ces réponses"));
        q.add(typed(2,"Git","Commande à écrire","Initialise le dossier courant comme dépôt Git.","Guide Git débutant Ubuntu — git init crée les métadonnées .git. Il n’envoie rien sur GitHub.","mkdir projet\ncd projet\ngit init","git init"));
        q.add(typed(2,"Git","Corriger une commande","Prépare uniquement README.md pour le prochain commit. Corrige : git push README.md","Guide Git débutant Ubuntu — git add choisit le contenu du prochain commit. Push envoie des commits déjà créés.","git add README.md\ngit diff --staged","git add README.md"));
        q.add(typed(2,"Git","Ordre à rétablir","Classe ces étapes : 1 = commit, 2 = modifier le fichier, 3 = add. Réponds avec trois chiffres séparés par des espaces.","Guide Git débutant Ubuntu — on modifie d’abord le fichier, on place le contenu dans l’index, puis on crée le commit.","nano README.md\ngit add README.md\ngit commit -m 'Ajout'","2 3 1"));
        q.add(new MainActivity.Question(2,"Git","Tu as modifié README.md sans add ni commit. Quelle action publie cette nouvelle version à elle seule ?",2,"Guide Git débutant Ubuntu — ni status ni push ne crée un commit. Il faut add, commit puis push. L’état local n’est pas une synchronisation automatique.","git add README.md\ngit commit -m 'Mise à jour'\ngit push","git status","git push","Aucune de ces réponses"));
        q.add(typed(3,"SSH","Commande à écrire","Affiche la clé PUBLIQUE Ed25519 pour la copier sur GitHub. Tape la commande cat.","Mémo commandes Git/GitHub/SSH — seul le fichier .pub est destiné à GitHub. Ne publie jamais la clé privée sans .pub.","cat ~/.ssh/id_ed25519.pub","cat ~/.ssh/id_ed25519.pub"));
        q.add(typed(3,"Git","Corriger une commande","Affiche les URL fetch et push d’origin. Corrige : git remote --v","Mémo commandes Git/GitHub/SSH — l’option courte est -v. Ces URL ne prouvent pas qu’une authentification a réussi.","git remote -v","git remote -v"));
        q.add(typed(3,"SSH","Commande à écrire","La clé existe et ssh-agent fonctionne. Charge cette clé dans l’agent.","Mémo commandes Git/GitHub/SSH — ssh-add charge la clé privée dans l’agent local ; git add prépare des fichiers pour un commit.","ssh-add ~/.ssh/id_ed25519","ssh-add ~/.ssh/id_ed25519"));
        q.add(new MainActivity.Question(3,"SSH","Piège : que faut-il coller comme clé publique dans GitHub ?",2,"Mémo commandes Git/GitHub/SSH — il faut la ligne du fichier id_ed25519.pub. Ni le secret privé ni son empreinte SHA256 ne remplace cette ligne.","cat ~/.ssh/id_ed25519.pub","Le contenu de id_ed25519","L’empreinte SHA256 uniquement","Aucune de ces réponses"));
        q.add(typed(4,"Branches","Commande à écrire","Crée la branche cheese et place-toi dessus en une commande.","Guide Git/GitHub Branches et Flow — switch -c crée et sélectionne la branche. branch cheese seul ne change pas de branche.","git switch -c cheese\ngit branch","git switch -c cheese","git checkout -b cheese"));
        q.add(typed(4,"Branches","Prédire le résultat","Tu es sur cheese et crées un commit. Le pointeur de main avance-t-il ? Réponds oui ou non.","Guide Git/GitHub Branches et Flow — seul le pointeur de la branche courante avance. Publier cheese ne fusionne pas main.","git switch cheese\ngit commit -m 'Pizza'\n# main reste sur son commit","non","Non"));
        q.add(typed(4,"Branches","Commande à écrire","Publie la branche cheese sur origin, sans demander de fusion.","Guide Git/GitHub Branches et Flow — push publie la branche. Une fusion ou Pull Request est une opération distincte.","git push origin cheese","git push origin cheese","git push -u origin cheese"));
        q.add(new MainActivity.Question(4,"Branches","Quelle commande supprime UNIQUEMENT la branche cheese distante ?",4,"Guide Git/GitHub Branches et Flow — les quatre commandes proposées sont différentes : suppression locale, publication, changement de branche et fusion. La commande attendue est git push origin --delete cheese.","git push origin --delete cheese","git branch -d cheese","git push origin cheese","git switch cheese","git merge cheese","Aucune de ces réponses"));
        q.add(typed(5,"Conflits","Ordre à rétablir","Après un conflit, classe : 1 = git add, 2 = éditer et retirer les marqueurs, 3 = git commit, 4 = relire git diff --staged. Réponds avec quatre chiffres.","Guide Git/GitHub Merge et Conflits — on décide du contenu, on l’indexe, on vérifie le résultat puis on crée le commit. Add ne valide pas la logique de ta résolution.","nano README.md\ngit add README.md\ngit diff --staged\ngit commit -m 'Résolution'","2 1 4 3"));
        q.add(typed(5,"Conflits","Commande à écrire","Une fusion est en cours. Annule-la avec la commande Git dédiée.","Guide Git/GitHub Merge et Conflits — merge --abort tente de revenir à l’état précédent. Ce n’est pas la même opération qu’effacer les marqueurs à la main.","git merge --abort","git merge --abort"));
        q.add(typed(5,"Conflits","Diagnostic","git add comprend-il automatiquement si ta résolution du conflit est correcte ? Réponds oui ou non.","Guide Git/GitHub Merge et Conflits — add enregistre ta version dans l’index. Tu dois relire, tester et consulter le diff staged.","git add README.md\ngit diff --staged","non","Non"));
        q.add(new MainActivity.Question(5,"Conflits","Un conflit est présent dans README.md. Quelle commande résout à elle seule correctement son contenu ?",4,"Guide Git/GitHub Merge et Conflits — aucune commande proposée ne décide du contenu voulu. Il faut lire les versions, éditer le fichier, retirer les marqueurs puis vérifier avant commit.","nano README.md\ngit add README.md\ngit diff --staged","git status","git add README.md","git push","git log","Aucune de ces réponses"));
        q.add(new MainActivity.Question(1,"Bash","Quelle commande crée un dossier cours ? « Aucune » peut aussi être choisie.",0,"Fiche Bash S01 — mkdir crée un dossier. Touch crée un fichier, cd change de position, pwd affiche le chemin.","mkdir cours","mkdir cours","touch cours","cd cours","pwd cours","Aucune de ces réponses"));
        q.add(new MainActivity.Question(2,"Git","Quelle commande montre les changements déjà placés dans l’index ?",0,"Guide Git débutant Ubuntu — diff --staged compare l’index au dernier commit. Diff seul montre les changements non indexés.","git diff --staged","git diff --staged","git diff","git push","git remote -v","Aucune de ces réponses"));
        q.add(new MainActivity.Question(3,"SSH","Quelle commande vérifie l’authentification SSH auprès de GitHub ?",0,"Mémo Git/GitHub/SSH — ssh -T teste l’authentification. GitHub ne fournit pas de shell interactif.","ssh -T git@github.com","ssh -T git@github.com","git status","git add .","git init","Aucune de ces réponses"));
        q.add(new MainActivity.Question(4,"Branches","Quelle commande change vers la branche main déjà existante ?",0,"Guide Git/GitHub Branches et Flow — switch sélectionne une branche existante. -c demanderait d’en créer une.","git switch main","git switch main","git switch -c main","git push main","git remote main","Aucune de ces réponses"));
        q.add(new MainActivity.Question(5,"Conflits","Après édition du conflit, quelle commande permet de vérifier le contenu placé dans l’index ?",0,"Guide Git/GitHub Merge et Conflits — diff --staged permet de relire la version préparée avant commit.","git add README.md\ngit diff --staged","git diff --staged","git push","git branch","git remote -v","Aucune de ces réponses"));
        return q;
    }
}
