package com.ghiles.quizubuntu;

import java.util.ArrayList;
import java.util.List;

/** Questions restricted to the five supplied PDF course documents. */
final class PdfQuizBank {
    static List<MainActivity.Question> questions() {
        List<MainActivity.Question> bank = new ArrayList<>();
        bank.add(new MainActivity.Question(1, "Bash", "Que désigne le chemin « . » ?", 0, "Fiche Bash S01 : chemins Linux", "ls .", "Le dossier courant", "Le dossier parent", "La racine", "Le dossier personnel"));
        bank.add(new MainActivity.Question(1, "Bash", "Que désigne le chemin « .. » ?", 0, "Fiche Bash S01 : chemins Linux", "cd ..", "Le dossier parent", "La racine du disque", "Un fichier caché", "Le dossier personnel"));
        bank.add(new MainActivity.Question(1, "Bash", "Quelle commande crée plusieurs niveaux de dossiers en une fois ?", 0, "Fiche Bash S01 : mkdir -p crée les parents absents", "mkdir -p a/b/c", "mkdir -p a/b/c", "mkdir a/b/c sans parents", "touch a/b/c", "cd -p a/b/c"));
        bank.add(new MainActivity.Question(1, "Bash", "Que fait Ctrl+C pendant une commande ?", 0, "Fiche Bash S01 : interruption", "Ctrl+C", "Demande son interruption", "Copie forcément le texte", "Supprime le dossier", "Ferme forcément Ubuntu"));
        bank.add(new MainActivity.Question(1, "Bash", "Quelle commande affiche les commandes précédemment saisies ?", 0, "Fiche Bash S01 : historique", "history", "history", "clear", "pwd", "rmdir"));
        bank.add(new MainActivity.Question(2, "Bash", "Quel est l’effet de > fichier.txt sans texte à gauche ?", 0, "Fiche Bash S01 : redirection et gestion des fichiers", "> fichier.txt", "Créer ou vider le fichier", "Supprimer le fichier", "Afficher le fichier", "Renommer le fichier"));
        bank.add(new MainActivity.Question(2, "Bash", "Quelle commande ajoute une ligne sans effacer le contenu existant ?", 0, "Fiche Bash S01 : >> ajoute à la fin", "echo suite >> fichier.txt", "echo suite >> fichier.txt", "echo suite > fichier.txt", "rm fichier.txt", "touch suite"));
        bank.add(new MainActivity.Question(2, "Bash", "Quand rmdir dossier peut-il réussir ?", 0, "Fiche Bash S01 : rmdir supprime un dossier vide", "rmdir dossier", "Lorsque le dossier est vide", "Seulement si Git est installé", "Uniquement si le dossier contient un fichier", "Quand le dossier est une branche"));
        bank.add(new MainActivity.Question(2, "Bash", "Quelle commande copie un dossier avec son contenu ?", 0, "Fiche Bash S01 : copie récursive", "cp -r dossier copie", "cp -r dossier copie", "cp dossier sans option", "mv dossier copie", "cat dossier copie"));
        bank.add(new MainActivity.Question(2, "Git", "Quelle commande vérifie la version de Git installée ?", 0, "Guide Git débutant Ubuntu : vérifier l’installation", "git --version", "git --version", "git init", "git status", "git config version"));
        bank.add(new MainActivity.Question(2, "Git", "Quelle commande configure le nom utilisé dans les prochains commits ?", 0, "Guide Git débutant Ubuntu : configuration de l’identité", "git config --global user.name \"Ton Nom\"", "git config --global user.name \"Ton Nom\"", "git login \"Ton Nom\"", "git remote user.name \"Ton Nom\"", "git commit user.name"));
        bank.add(new MainActivity.Question(3, "Git", "Après git add puis une nouvelle modification, que contient le prochain commit ?", 0, "Guide Branches et flow : HEAD, index et working directory sont trois états distincts", "git add README.md", "La version préparée lors de git add", "Toujours le dernier contenu du fichier", "Tous les fichiers du disque", "Uniquement les fichiers distants"));
        bank.add(new MainActivity.Question(3, "Git", "Quelle commande compare l’index au dernier commit ?", 0, "Guide Branches et flow : diff de l’index vers HEAD", "git diff --staged", "git diff --staged", "git diff", "git remote -v", "git branch -a"));
        bank.add(new MainActivity.Question(3, "Git", "Quelle commande compare le dossier de travail à l’index ?", 0, "Guide Branches et flow : diff du working directory vers l’index", "git diff", "git diff", "git diff --staged", "git push", "git fetch"));
        bank.add(new MainActivity.Question(3, "Git", "Un git commit normal remplit-il le commit précédent ?", 0, "Guide Branches et flow : un commit normal crée un nouvel objet avec un parent", "git commit -m \"Ajout\"", "Non, il crée un nouveau commit", "Oui, toujours", "Seulement sur main", "Seulement après push"));
        bank.add(new MainActivity.Question(3, "Git", "Quelle commande indique les URL des dépôts distants ?", 0, "Guide débutant Ubuntu et mémo SSH : vérifier la destination de push", "git remote -v", "git remote -v", "git log -p", "git status", "git config user.name"));
        bank.add(new MainActivity.Question(3, "Git", "Comment afficher l’origine des valeurs de configuration ?", 0, "Mémo Git/GitHub/SSH : diagnostic de configuration", "git config --list --show-origin", "git config --list --show-origin", "git origin --list", "git remote --config", "git show config"));
        bank.add(new MainActivity.Question(3, "Git", "Comment supprimer la valeur globale de user.email ?", 0, "Mémo Git/GitHub/SSH : --unset retire une valeur", "git config --global --unset user.email", "git config --global --unset user.email", "git config --global user.email delete", "git remove email", "git remote remove email"));
        bank.add(new MainActivity.Question(4, "Branches", "Créer une branche copie-t-il tous les commits ?", 0, "Guide Branches et flow : branche = pointeur nommé", "git switch -c cheese", "Non, cela crée un pointeur vers un commit", "Oui, cela double l’historique", "Oui, cela crée un autre dépôt", "Cela supprime main"));
        bank.add(new MainActivity.Question(4, "Branches", "Après un commit sur cheese, que devient main ?", 0, "Guide Branches et flow : seule la branche courante avance", "git commit -m \"Pizzas\"", "Son pointeur reste inchangé", "Il avance automatiquement", "Il est supprimé", "Il devient origin"));
        bank.add(new MainActivity.Question(4, "Branches", "Que fait git push origin cheese ?", 0, "Guide Branches et flow : push n’est pas une fusion", "git push origin cheese", "Publie cheese sur le dépôt distant", "Fusionne automatiquement cheese dans main", "Supprime cheese en local", "Change la branche courante"));
        bank.add(new MainActivity.Question(4, "Branches", "Après une fusion sur GitHub, comment actualiser main local ?", 0, "Guide Branches et flow : synchronisation après Pull Request", "git switch main && git pull origin main", "Revenir sur main puis git pull origin main", "Seulement git status", "Supprimer origin", "Créer une branche cheese"));
        bank.add(new MainActivity.Question(4, "Branches", "git branch -d cheese supprime-t-il la branche sur GitHub ?", 0, "Guide Branches et flow : nettoyage local et distant distincts", "git branch -d cheese", "Non, seulement le pointeur local", "Oui, toujours", "Oui, après un commit", "Cela supprime tout l’historique"));
        bank.add(new MainActivity.Question(4, "Branches", "Quelle commande vérifie les branches réellement présentes chez origin ?", 0, "Guide Branches et flow : lecture directe des références distantes", "git ls-remote --heads origin", "git ls-remote --heads origin", "git branch", "git status", "git log -p"));
        bank.add(new MainActivity.Question(4, "SSH", "Quel fichier peut être ajouté aux clés SSH de GitHub ?", 0, "Mémo Git/GitHub/SSH : seule la clé publique est destinée à GitHub", "cat ~/.ssh/id_ed25519.pub", "~/.ssh/id_ed25519.pub", "~/.ssh/id_ed25519", "Le mot de passe GitHub", "Le fichier .git/index"));
        bank.add(new MainActivity.Question(4, "SSH", "Une empreinte SHA256 remplace-t-elle la clé publique dans GitHub ?", 0, "Mémo Git/GitHub/SSH : empreinte et clé publique sont différentes", "ssh-keygen -lf ~/.ssh/id_ed25519.pub", "Non, elle sert à identifier la clé", "Oui, toujours", "Seulement en HTTPS", "Seulement après git init"));
        bank.add(new MainActivity.Question(4, "SSH", "Quel outil mémorise la clé SSH déverrouillée ?", 0, "Mémo Git/GitHub/SSH : agent de clés", "eval \"$(ssh-agent -s)\"", "ssh-agent", "git add", "git remote", "nano"));
        bank.add(new MainActivity.Question(4, "SSH", "Quelle commande charge la clé privée dans l’agent ?", 0, "Mémo Git/GitHub/SSH : charger la clé avec ssh-add", "ssh-add ~/.ssh/id_ed25519", "ssh-add ~/.ssh/id_ed25519", "git add ~/.ssh/id_ed25519", "cat ~/.ssh/id_ed25519", "git push ~/.ssh/id_ed25519"));
        bank.add(new MainActivity.Question(4, "SSH", "Comment remplacer l’URL d’un remote origin déjà présent ?", 0, "Mémo Git/GitHub/SSH : set-url modifie un remote existant", "git remote set-url origin git@github.com:USER/REPO.git", "git remote set-url origin URL", "git remote add origin URL une seconde fois", "git init origin URL", "git commit origin URL"));
        bank.add(new MainActivity.Question(4, "Git", "À quoi sert -u lors du premier push ?", 0, "Mémo Git/GitHub/SSH : suivi upstream", "git push -u origin main", "Configurer le suivi de la branche distante", "Fusionner deux branches", "Annuler le dernier commit", "Créer une clé SSH"));
        bank.add(new MainActivity.Question(5, "Conflits", "Quelles versions sont comparées dans un merge à trois voies ?", 0, "Guide Merge & Conflits : base commune et deux versions", "git pull origin main", "BASE, OURS et THEIRS", "Trois copies de HEAD", "main, master et develop obligatoirement", "Trois fichiers choisis au hasard"));
        bank.add(new MainActivity.Question(5, "Conflits", "Après avoir résolu un conflit, que faut-il enlever du fichier ?", 0, "Guide Merge & Conflits : nettoyer les marqueurs après décision", "<<<<<<< / ======= / >>>>>>>", "Tous les marqueurs de conflit", "Tout le fichier", "La branche main", "Le dossier .git"));
        bank.add(new MainActivity.Question(5, "Conflits", "git add vérifie-t-il que la résolution d’un conflit est correcte ?", 0, "Guide Merge & Conflits : toujours relire le contenu et le diff staged", "git add README.md && git diff --staged", "Non, il marque la version comme résolue", "Oui, il comprend l’intention", "Oui, il supprime les marqueurs", "Non, il lance seulement un push"));
        bank.add(new MainActivity.Question(5, "Conflits", "Pourquoi git diff peut-il être vide après git add ?", 0, "Guide Merge & Conflits : utiliser git diff --staged après add", "git diff --staged", "Les modifications sont déjà dans l’index", "Les commits sont supprimés", "Le remote est effacé", "GitHub est déconnecté"));
        bank.add(new MainActivity.Question(5, "Git", "git fetch -a signifie-t-il récupérer tous les remotes ?", 0, "Guide Merge & Conflits : erreur -a versus --all", "git fetch --all", "Non, -a signifie append ; utiliser --all", "Oui, a signifie all", "Oui, mais seulement avec SSH", "Non, cela supprime les remotes"));
        bank.add(new MainActivity.Question(5, "Conflits", "Pourquoi un push normal peut-il être refusé après une modification sur GitHub ?", 0, "Guide Merge & Conflits : intégrer les changements distants avant publication", "git pull origin main", "Le distant contient des commits encore inconnus localement", "Git interdit deux appareils", "Le nom main est invalide", "Un push efface toujours le local"));
        bank.add(new MainActivity.Question(5, "Git", "Que fait git pull --rebase origin main ?", 0, "Mémo Git/GitHub/SSH : rebase après récupération", "git pull --rebase origin main", "Récupère le distant puis rejoue les commits locaux", "Supprime tous les commits locaux", "Ne fait que lire les URL", "Force le push"));
        bank.add(new MainActivity.Question(5, "Git", "Quand --allow-unrelated-histories peut-il être nécessaire ?", 0, "Mémo Git/GitHub/SSH : historiques sans ancêtre commun", "git pull origin main --allow-unrelated-histories", "Pour fusionner deux historiques initialisés séparément", "Pour tous les push", "Pour renommer un fichier", "Pour créer une clé SSH"));
        bank.add(new MainActivity.Question(5, "Git", "Que vérifie --force-with-lease avant un push forcé ?", 0, "Mémo Git/GitHub/SSH : le lease protège contre un changement distant inattendu ; cela reste une réécriture", "git push --force-with-lease origin main", "Que le distant correspond encore à la référence attendue", "Que tous les fichiers sont vides", "Que le dépôt est public", "Que main a été supprimée"));
        bank.add(new MainActivity.Question(5, "Conflits", "Combien de parents possède le merge commit présenté dans le guide ?", 0, "Guide Merge & Conflits : le merge relie les deux histoires", "git log --graph --oneline --decorate --all", "Deux", "Aucun", "Un seul", "Toujours trois"));
        return bank;
    }
}
