package com.ghiles.quizubuntu;
import java.util.*;
import com.ghiles.quizubuntu.VirtualMachine.Result;
/** Stateful VirtualBox teaching model: configurations, media and power state, no guest OS execution. */
final class S03VirtualBox {
    private final VirtualMachine fs;
    static final class Machine {
        String name,id,state="poweroff";
        final Map<String,String> config=new LinkedHashMap<>(),controllers=new LinkedHashMap<>(),attachments=new LinkedHashMap<>();
        final Map<String,Map<String,String>> snapshots=new LinkedHashMap<>();
        Machine(String name){this.name=name;id=UUID.nameUUIDFromBytes(name.getBytes(java.nio.charset.StandardCharsets.UTF_8)).toString();config.put("memory","128");config.put("vram","16");config.put("ostype","Ubuntu_64");}
    }
    final Map<String,Machine> machines=new LinkedHashMap<>();
    final Map<String,String> media=new LinkedHashMap<>();
    S03VirtualBox(VirtualMachine fs){this.fs=fs;}
    void reset(){machines.clear();media.clear();}
    private String required(Map<String,String> options,String key){String value=options.get(key);if(value==null||value.isEmpty())throw new IllegalArgumentException("VBoxManage: option requise --"+key);return value;}
    private Map<String,String> options(List<String>a,int start,String... allowed){Map<String,String> out=new LinkedHashMap<>();Set<String> names=new HashSet<>(Arrays.asList(allowed));for(int i=start;i<a.size();i++){String name=a.get(i).replaceFirst("^--","");if(!a.get(i).startsWith("--")||!names.contains(name))throw new IllegalArgumentException("VBoxManage: option non prise en charge : "+a.get(i));if(name.equals("register")||name.equals("delete")){out.put(name,"true");continue;}if(++i>=a.size())throw new IllegalArgumentException("VBoxManage: valeur manquante");out.put(name,a.get(i));}return out;}
    private Machine machine(String name){for(Machine m:machines.values())if(m.name.equals(name)||m.id.equals(name.replace("{","").replace("}","")))return m;throw new IllegalArgumentException("VBoxManage: machine introuvable : "+name);}
    private void off(Machine m){if(!m.state.equals("poweroff"))throw new IllegalArgumentException("VBoxManage: éteins la VM avant de modifier sa configuration");}
    Result handle(List<String>a){
        if(a.isEmpty()||!a.get(0).equalsIgnoreCase("VBoxManage"))return null;
        if(a.size()<2)return Result.error("VBoxManage: sous-commande requise");String cmd=a.get(1);
        if(cmd.equals("--version"))return Result.normal("VirtualBox 7 — modèle pédagogique S03\n");
        if(cmd.equals("list")){if(a.size()!=3||(!a.get(2).equals("vms")&&!a.get(2).equals("runningvms")))return Result.error("Usage : VBoxManage list vms|runningvms");StringBuilder out=new StringBuilder();for(Machine m:machines.values())if(a.get(2).equals("vms")||m.state.equals("running"))out.append("\""+m.name+"\" {"+m.id+"}\n");return Result.normal(out.toString());}
        if(cmd.equals("createvm")){Map<String,String> o=options(a,2,"name","ostype","register","basefolder");String name=required(o,"name");if(machines.containsKey(name))return Result.error("VBoxManage: nom déjà utilisé");if(!o.containsKey("register"))return Result.error("Atelier : --register est requis pour enregistrer cette VM");Machine m=new Machine(name);m.config.put("ostype",o.getOrDefault("ostype","Ubuntu_64"));String dir=fs.resolve(o.getOrDefault("basefolder","~/VirtualBox VMs"))+"/"+name;fs.ensureDir(dir);m.config.put("directory",dir);machines.put(name,m);save(m);return Result.normal("VM virtuelle enregistrée : "+name+"\nUUID: "+m.id+"\n");}
        if(cmd.equals("createmedium")||cmd.equals("clonemedium")){
            if(a.size()<3||!a.get(2).equals("disk"))return Result.error("VBoxManage: type disk requis");String path,format;
            if(cmd.equals("createmedium")){Map<String,String> o=options(a,3,"filename","size","format");path=fs.resolve(required(o,"filename"));int size=Integer.parseInt(required(o,"size"));if(size<=0)return Result.error("Taille positive en Mo requise");format=o.getOrDefault("format","VDI");if(!Arrays.asList("VDI","VMDK").contains(format.toUpperCase(Locale.ROOT)))return Result.error("Format attendu : VDI ou VMDK");}
            else{if(a.size()<5)return Result.error("clonemedium: source et destination requises");String source=fs.resolve(a.get(3));if(!media.containsKey(source))return Result.error("Disque source inconnu");path=fs.resolve(a.get(4));format=options(a,5,"format").getOrDefault("format",media.get(source));}
            if(fs.files.containsKey(path))return Result.error("Destination déjà présente");fs.ensureDir(fs.parent(path));fs.files.put(path,"Disque virtuel pédagogique "+format+"\n");media.put(path,format);return Result.normal("Disque virtuel créé : "+path+"\n");
        }
        if(a.size()<3)return Result.error("VBoxManage: VM requise");Machine m=machine(a.get(2));
        if(cmd.equals("showvminfo")){StringBuilder out=new StringBuilder("Name: "+m.name+"\nUUID: "+m.id+"\nState: "+m.state+"\n");for(Map.Entry<String,String>e:m.config.entrySet())out.append(e.getKey()+": "+e.getValue()+"\n");for(Map.Entry<String,String>e:m.controllers.entrySet())out.append("Controller: "+e.getKey()+" "+e.getValue()+"\n");for(Map.Entry<String,String>e:m.attachments.entrySet())out.append(e.getKey()+": "+e.getValue()+"\n");return Result.normal(out.toString());}
        if(cmd.equals("modifyvm")){off(m);Map<String,String> o=options(a,3,"memory","vram","graphicscontroller","nic1");for(String key:Arrays.asList("memory","vram"))if(o.containsKey(key)&&Integer.parseInt(o.get(key))<=0)return Result.error("Mémoire positive en Mo requise");if(o.containsKey("nic1")&&!Arrays.asList("nat","none","bridged","hostonly","intnet").contains(o.get("nic1")))return Result.error("Mode réseau invalide");m.config.putAll(o);save(m);return Result.normal("");}
        if(cmd.equals("storagectl")){off(m);Map<String,String> o=options(a,3,"name","add","controller");String name=required(o,"name"),bus=required(o,"add");if(!Arrays.asList("sata","ide").contains(bus.toLowerCase(Locale.ROOT)))return Result.error("Bus attendu : sata ou ide");if(m.controllers.containsKey(name))return Result.error("Contrôleur déjà présent");m.controllers.put(name,bus+" "+o.getOrDefault("controller",""));save(m);return Result.normal("");}
        if(cmd.equals("storageattach")){off(m);Map<String,String>o=options(a,3,"storagectl","port","device","type","medium");String ctl=required(o,"storagectl");if(!m.controllers.containsKey(ctl))return Result.error("Contrôleur absent");String port=required(o,"port"),device=required(o,"device"),type=required(o,"type"),medium=required(o,"medium");if(Integer.parseInt(port)<0||Integer.parseInt(device)<0)return Result.error("Port/device invalide");if(!Arrays.asList("hdd","dvddrive").contains(type))return Result.error("Type attendu : hdd ou dvddrive");String p=fs.resolve(medium);if(type.equals("hdd")&&!media.containsKey(p))return Result.error("Disque absent");if(type.equals("dvddrive")&&!medium.equals("emptydrive")&&!fs.files.containsKey(p))return Result.error("ISO absent du modèle ; crée un fichier ISO fictif avec touch pour cet atelier");m.attachments.put(ctl+":"+port+":"+device,type+" "+medium);save(m);return Result.normal("");}
        if(cmd.equals("startvm")){Map<String,String>o=options(a,3,"type");String type=o.getOrDefault("type","gui");if(!Arrays.asList("gui","headless","separate").contains(type))return Result.error("Type de démarrage invalide");if(!m.state.equals("poweroff"))return Result.error("VM déjà démarrée");m.state="running";return Result.normal("État simulé : "+m.name+" démarrée ("+type+"). Aucun OS invité n'est lancé sur Android.\n");}
        if(cmd.equals("controlvm")){if(a.size()!=4)return Result.error("controlvm: poweroff, acpipowerbutton, pause ou resume requis");String action=a.get(3);if(action.equals("resume")&&m.state.equals("paused"))m.state="running";else if(m.state.equals("running")&&action.equals("pause"))m.state="paused";else if(!m.state.equals("poweroff")&&(action.equals("poweroff")||action.equals("acpipowerbutton")))m.state="poweroff";else return Result.error("Transition d'état impossible");return Result.normal("");}
        if(cmd.equals("snapshot")){if(a.size()<4)return Result.error("snapshot: action requise");String action=a.get(3);if(action.equals("list"))return Result.normal(String.join("\n",m.snapshots.keySet())+(m.snapshots.isEmpty()?"":"\n"));if(a.size()!=5)return Result.error("snapshot: nom requis");String name=a.get(4);if(action.equals("take")){if(m.snapshots.containsKey(name))return Result.error("Snapshot déjà présent");Map<String,String> snap=new LinkedHashMap<>(m.config);for(Map.Entry<String,String>e:m.controllers.entrySet())snap.put("ctl:"+e.getKey(),e.getValue());for(Map.Entry<String,String>e:m.attachments.entrySet())snap.put("att:"+e.getKey(),e.getValue());m.snapshots.put(name,snap);return Result.normal("Snapshot pédagogique de configuration enregistré.\n");}if(action.equals("restore")){off(m);if(!m.snapshots.containsKey(name))return Result.error("Snapshot absent");m.config.clear();m.controllers.clear();m.attachments.clear();for(Map.Entry<String,String>e:m.snapshots.get(name).entrySet()){if(e.getKey().startsWith("ctl:"))m.controllers.put(e.getKey().substring(4),e.getValue());else if(e.getKey().startsWith("att:"))m.attachments.put(e.getKey().substring(4),e.getValue());else m.config.put(e.getKey(),e.getValue());}save(m);return Result.normal("Configuration restaurée (pas d'OS invité dans ce modèle).\n");}return Result.error("Action snapshot non prise en charge");}
        return Result.error("VBoxManage: sous-commande non prise en charge : "+cmd);
    }
    private void save(Machine m){String dir=m.config.get("directory");fs.files.put(dir+"/"+m.name+".vbox","VM pédagogique\n"+m.config+"\n"+m.controllers+"\n"+m.attachments+"\n");}
}
